# Generated by Django 4.2.10 on 2024-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
